# Dataset selection
selected-dataset: 'CICIDS2017' #"CICEVSE_Network2024" # CICEVSE_PowerB2024 # "CICIoV2024" "CICIDS2017"
polyak: True
# Training and experiment setup
setup:
  params:
    train-batch-size: 32
    val-batch-size: 512
    epochs: 10
    lr: 0.004
    n_episodes: 200
    n_support: 40
    n_query: 20
    n_experiments: 40
    n_samples: 200
    sample_per_class: 2

  scenario_config:
    weights: ["euclidean", "chebyshev", "cosine", "wasserstein"]
    vals: ['1/4', '1/4', '1/4', '1/4']

# Output configuration
output:
  train-history: "train_history" # Directory for training outputs
  best_models: "outputs/models" # Directory for saving best models
# Additional configuration
logging:
  level: "INFO"
  save_frequency: 10 # Save checkpoints every N epochs

# # Hardware configuration
# hardware:
#   gpu_id: 0
#   num_workers: 4 # Number of data loading workers
